Bump all outdated dependencies
jupyterlab/jupyterlab-latex pull request #188
Opened 2022-01-27 00:56 UTC by ktaletsk

Bump minor package version to 3.1.1

2022-08-19 09:05 UTC, fcollonval requested changes
Thanks @ktaletsk one small comment and could you rebase this PR and update the yarn.lock please?

2022-08-19 09:05 UTC, fcollonval commented on package.json
> +  "version": "3.1.1",
I would upgrade it to 3.2.0 to reflect the dependency upgrade as a patch version is expected to be a simple replacement.

2022-11-25 13:49 UTC, fcollonval commented on docs/changelog.md
> +- **3.1.1**:
```suggestion
- **3.2.0**:
```

2023-05-14 12:55 UTC, ktaletsk commented
Closing in favor of #213

2023-05-14 12:55 UTC, closed without merging